- id: '1694950719513'
  alias: Battery Level Automation
  description: Show Pinhas battery levels
  trigger:
  - type: battery_level
    platform: device
    device_id: 7c686ea37d03803fcad1e50324f58598
    entity_id: 24ce5169e0de3d13e764466bb8098e6f
    domain: sensor
    above: 50
  condition: []
  action:
  - service: notify.home_schedule
    data:
      message: '*Battary Level*

        {% if states(''sensor.shula_mastula_phone_battery_level'') | float(0) > 50
        %} High :white_check_mark: {% elif states(''sensor.shula_mastula_phone_battery_level'')
        | float(0) < 10 %} Mid :white_check_mark: {% else %} Low :rotating_light:
        {% endif %} {{states(''sensor.shula_mastula_phone_battery_level'')}}'
  mode: single
- id: '1694978187855'
  alias: New automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.myip
    - media_player.shulamastula
    - switch.switcher_touch_5a43
    - sensor.shula_mastula_phone_battery_level
    - sensor.shula_mastula_phone_battery_state
    - camera.chuangmi_029a02_f1a3_motion_event
    to:
  condition: []
  action:
  - service: notify.home_schedule
    data:
      message: "*State Changed* \n_Pinhas Phone_\n  {% if states('sensor.shula_mastula_phone_battery_level')
        | float(0) > 50 %} :battery: {% else %} :low_battery: {% endif %} Battery:
        {{ states('sensor.shula_mastula_phone_battery_level') }}%\n  {% if states('sensor.shula_mastula_phone_battery_state')
        == Charging %} :zap: {% else %} :electric_plug: {% endif %} {{ states('sensor.shula_mastula_phone_battery_state')
        }} \n_Boiler_\n  {% if states('switch.switcher_touch_5a43') == \"on\" %} :large_green_circle:
        {% else %} :red_circle: {% endif %} Power: {{ states('switch.switcher_touch_5a43')
        }}\n  {% if states('sensor.switcher_touch_5a43_remaining_time') | string !=
        \"00:00:00\" %} :timer_clock: {{ states('sensor.switcher_touch_5a43_remaining_time')
        }} {% endif %}\n_TV_\n  {% if states('media_player.shulamastula') == \"on\"
        %} :large_green_circle: {% else %} :red_circle: {% endif %} Power: {{ states('media_player.shulamastula')
        }}\n_Camera_  \n  {% if states('switch.chuangmi_029a02_f1a3_switch_status')
        == \"on\" %} :large_green_circle: {% else %} :red_circle: {% endif %} Power:
        {{ states('switch.chuangmi_029a02_f1a3_switch_status') }}\n  {% if states('camera.chuangmi_029a02_f1a3_camera_control')
        == \"streaming\" %} :movie_camera: {% else %} :red_circle: {% endif %} Control:
        {{ states('camera.chuangmi_029a02_f1a3_camera_control') }}"
  mode: single
